name: MSYS2 Build

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          make
          mingw-w64-x86_64-gcc

    - shell: msys2 {0}
      run: |
        cd Document/MinGW
        make

    - uses: actions/upload-artifact@v1
      with:
        name: res
        path: ${{ github.workspace }}
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
    
    - uses: actions/download-artifact@v3
      with:
        name: res
        path: ~/result
        
    - uses: geekyeggo/delete-artifact@v1
      with:
        name: res
    
    - uses: papeloto/action-zip@v1
      with:
        files: ~/result
        dest: EDCB.zip

    - uses: adityak74/google-drive-upload-git-action@main
      with:
        folderId: 1HXQxN9yONioKj_MxKqPuCYUQlmWlEhKJ
        filename: "EDCB.zip"
        credentials: ${{ secrets.MKARAKI_GDRIVE_SRVACCOUNT }}
